apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceiba-deployment
  labels:
    app: ceiba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ceiba
  template:
    metadata:
      labels:
        app: ceiba
    spec:
      containers:
      - name: ceiba
        image: shoyos29/consignataria:5.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: ceiba-service
spec:
  type: LoadBalancer
  selector:
    app: ceiba
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080